env:
  node: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  warnOnUnsupportedTypeScriptVersion: true
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  '@typescript-eslint/no-inferrable-types': 0
  '@typescript-eslint/indent': 
    - error
    - 2
    - 'SwitchCase': 1
  'arrow-spacing': error
  'comma-dangle':
    - warn
    - always-multiline
  'keyword-spacing': error
  'linebreak-style': 
      - error
      - unix
  'no-trailing-spaces': error
  'prefer-const': error
  'semi': 
    - error
    - always
