name: push


on: push


env:
  GPR_TOKEN: ${{ secrets.NPM_TOKEN }}


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run eslint


  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test


  docker_build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    env:
      TAG: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: docker build . -t $TAG --build-arg NODE_AUTH_TOKEN=$GPR_TOKEN
      - run: docker push $TAG
