name: release


on: 
  release:
    types: [created]


jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    env:
      COMMIT_TAG: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}
      REPOSITORY: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: docker pull $COMMIT_TAG
      - run: docker tag $COMMIT_TAG $REPOSITORY:${GITHUB_REF:10}
      - run: docker push $REPOSITORY:${GITHUB_REF:10}
