name: release


on: 
  release:
    types: [created]


jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    env:
      REPOSITORY: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}
      COMMIT_TAG: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}
      DEPLOY_TAG: registry.heroku.com/${{ github.event.repository.name }}/worker

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: docker pull $COMMIT_TAG
      - run: docker tag $COMMIT_TAG $REPOSITORY:${GITHUB_REF:10}
      - run: docker push $REPOSITORY:${GITHUB_REF:10}

      # Deploy to Heroku
      - run: docker tag $COMMIT_TAG $DEPLOY_TAG
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_AUTH }}
      - run: docker push $DEPLOY_TAG
      - run: docker run --rm -e HEROKU_API_KEY=${{ secrets.HEROKU_AUTH }} wingrunr21/alpine-heroku-cli container:release worker --app=${{ github.event.repository.name }}
