name: stage


on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      COMMIT_TAG: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}
      HEROKU_TAG: registry.heroku.com/${{ github.event.repository.name }}-test/web:${{ github.sha }}

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: docker pull $COMMIT_TAG
      - run: docker tag $COMMIT_TAG $HEROKU_TAG
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_AUTH }}
      - run: docker push $HEROKU_TAG
      - run: docker run --rm -e HEROKU_API_KEY=${{ secrets.HEROKU_AUTH }} wingrunr21/alpine-heroku-cli container:release web --app=${{ github.event.repository.name }}-test
