name: tag


on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_CR: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}
      TEST_CR: registry.heroku.com/${{ github.event.repository.name }}-test/web

    steps:
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: docker pull $REPO_CR:${{ github.sha }}
      - run: docker tag $REPO_CR:${{ github.sha }} $REPO_CR:${GITHUB_REF:10}
      - run: docker push $REPO_CR:${GITHUB_REF:10}

      # Deploy to Heroku
      - run: docker tag $REPO_CR:${{ github.sha }} $TEST_CR:${GITHUB_REF:10}
      - uses: docker/login-action@v1
        with:
          registry: ${TEST_CR}
          username: _
          password: ${{ secrets.HEROKU_AUTH }}
      - run: docker push $TEST_CR:${GITHUB_REF:10}
      - run: docker run --rm -e HEROKU_API_KEY=${{ secrets.HEROKU_AUTH }} wingrunr21/alpine-heroku-cli container:release web --app=${{ github.event.repository.name }}-test
